[project]
name = "02-vector-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastembed>=0.7.1",
    "jupyter>=1.1.1",
    "qdrant-client[fastembed]>=1.14.3",
]
