[project]
name = "01-intro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "elasticsearch==8.17.2",
    "jupyter>=1.1.1",
    "requests>=2.32.3",
    "tiktoken>=0.9.0",
    "tqdm>=4.67.1",
]
