[project]
name = "dlt-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dlt[qdrant]>=1.13.0",
    "jupyter>=1.1.1",
    "qdrant-client[fastembed]>=1.14.3",
]
